apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: valhalla-image
  namespace: default
spec:
  type: image
  params:
    - name: url
      value: docker push laurentgrangeau/valhalla